---
#<% require 'poise_boiler' %>
<%= PoiseBoiler.kitchen(platforms: 'linux') %>

suites:
- name: default
  run_list:
  - recipe[application_ruby_test]
  - recipe[application_ruby_test::sinatra]
  - recipe[application_ruby_test::rails]
